version: 2.1
jobs:
  config_cisco:
    machine: true
    resource_class: network001/test001
    steps:
      - run:
          name: Install sshpass (for password auth)
          command: |
            set -eux
            if ! command -v sshpass >/dev/null 2>&1; then
              sudo apt-get update
              sudo apt-get install -y sshpass
            fi
      - run:
          name: Configure 3 Cisco devices (password auth + enable)
          command: |
            set -euo pipefail
            # ---- 必須環境変数 ----
            : "${CISCO_USER:?CISCO_USER is required}"
            : "${CISCO_PASS:?CISCO_PASS is required}"
            : "${CISCO_ENABLE:?CISCO_ENABLE is required}"
            # ---- ホスト一覧を環境変数から組み立て ----
            HOSTS="${CISCO_HOSTS:-}"
            if [ -z "$HOSTS" ]; then
              HOSTS="${CISCO_HOST1:-} ${CISCO_HOST2:-} ${CISCO_HOST3:-}"
            fi
            echo "Target hosts: $HOSTS"
            # ---- each host ----
            for H in $HOSTS; do
              [ -n "$H" ] || continue
              echo "===== Start $H ====="
              # known_hosts 準備（ホスト鍵変化にも対応）
              mkdir -p ~/.ssh && chmod 700 ~/.ssh
              touch ~/.ssh/known_hosts && chmod 600 ~/.ssh/known_hosts
              ssh-keygen -R "$H" >/dev/null 2>&1 || true
              ssh-keyscan -T 10 -H "$H" >> ~/.ssh/known_hosts || true
              # スモークテスト（show clock）
              echo "--- Smoke test: show clock on $H ---"
              sshpass -p "$CISCO_PASS" ssh -o StrictHostKeyChecking=accept-new \
                -o BatchMode=no \
                -o PreferredAuthentications=password \
                -o PubkeyAuthentication=no \
                -o Ciphers=aes256-cbc,aes192-cbc,aes128-cbc,3des-cbc \
                -o KexAlgorithms=diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group-exchange-sha1 \
                -o HostKeyAlgorithms=ssh-rsa \
                -o PubkeyAcceptedKeyTypes=ssh-rsa \
                "${CISCO_USER}@${H}" "show clock"
              # 設定投入（enable 必須。IOS 12.x 向けの古い暗号群を明示）
              echo "--- Configure hostname on $H ---"
              {
                printf '%s\r\n' \
                  'terminal length 0' \
                  'enable' \
                  "${CISCO_ENABLE}" \
                  'configure terminal' \
                  'no ip domain-lookup' \
                  'hostname GP-Router' \
                  'end' \
                  'write memory'
              } | sshpass -p "$CISCO_PASS" ssh -tt \
                    -o StrictHostKeyChecking=accept-new \
                    -o BatchMode=no \
                    -o PreferredAuthentications=password \
                    -o PubkeyAuthentication=no \
                    -o Ciphers=aes256-cbc,aes192-cbc,aes128-cbc,3des-cbc \
                    -o KexAlgorithms=diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group-exchange-sha1 \
                    -o HostKeyAlgorithms=ssh-rsa \
                    -o PubkeyAcceptedKeyTypes=ssh-rsa \
                    "${CISCO_USER}@${H}"
              echo "===== Done  $H ====="
            done
workflows:
  config:
    jobs:
      - config_cisco #2025/9/29 13:02