version: 2.1

jobs:
  config_cisco:
    machine: true
    resource_class: network001/test001
    steps:
      - checkout

      # （推奨）add_ssh_keysは使わず、環境変数で鍵を渡す
      # プロジェクト設定 or コンテキストに以下を登録しておく：
      #   CISCO_HOST            例: 192.0.2.10
      #   CISCO_USER            例: cisco-admin
      #   CISCO_SSH_KEY_B64     ※ ~/.ssh/id_rsa（秘密鍵ファイル）を base64 した文字列
      #   （必要なら）CISCO_PORT 例: 22

      - run:
          name: Prepare SSH key
          command: |
            set -euo pipefail
            : "${CISCO_HOST:?CISCO_HOST is required}"
            : "${CISCO_USER:?CISCO_USER is required}"
            : "${CISCO_SSH_KEY_B64:?CISCO_SSH_KEY_B64 is required}"
            : "${CISCO_PORT:=22}"

            mkdir -p ~/.ssh && chmod 700 ~/.ssh

            # 環境変数から秘密鍵を復元（CRLF除去して保存）
            echo "$CISCO_SSH_KEY_B64" | base64 -d | tr -d '\r' > ~/.ssh/id_rsa_cisco
            chmod 600 ~/.ssh/id_rsa_cisco

            # 鍵の妥当性チェック（ここで落ちたらフォーマット不正 or パスフレーズ付き）
            ssh-keygen -y -f ~/.ssh/id_rsa_cisco > ~/.ssh/id_rsa_cisco.pub

            # known_hosts 登録（失敗しても続行しない）
            ssh-keyscan -p "$CISCO_PORT" -T 10 -H "$CISCO_HOST" >> ~/.ssh/known_hosts

      - run:
          name: Configure Cisco Hostname
          command: |
            set -euo pipefail

            # 古いCisco向けに"ssh-rsa"や旧アルゴリズムを許可
            # 必要に応じて段階的に緩めてください
            SSH_OPTS="-p ${CISCO_PORT} -i ~/.ssh/id_rsa_cisco \
              -o IdentitiesOnly=yes \
              -o StrictHostKeyChecking=yes \
              -o BatchMode=yes \
              -o PubkeyAcceptedKeyTypes=+ssh-rsa \
              -o HostkeyAlgorithms=+ssh-rsa \
              -o KexAlgorithms=+diffie-hellman-group14-sha1 \
              -o Ciphers=+aes256-cbc"

            # まずは疎通チェック（詳細ログ）
            ssh -vvv $SSH_OPTS "${CISCO_USER}@${CISCO_HOST}" "show clock" || {
              echo "SSH login failed. Check key format/passphrase and Cisco pubkey registration."
              exit 1
            }

            # 実運用コマンド
            ssh -tt $SSH_OPTS "${CISCO_USER}@${CISCO_HOST}" \<<'EOS'
            terminal length 0
            configure terminal
            hostname GP-Router
            end
            write memory
            EOS

workflows:
  config:
    jobs:
      - config_cisco #202509251238