version: 2.1

jobs:
  mkdir_on_centos:
    machine:
      enabled: true
    resource_class: network001/test001
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "SHA256:S50sf0kpBGIIAvYaU48X07/Sl6+61J2hnrMbg3dibNY"

      - run:
          name: Add CentOS host key safely
          command: |
            set -euo pipefail
            mkdir -p ~/.ssh
            # 既存のエントリを削除（IP/ホスト名どちらでも）
            ssh-keygen -R "$CENTOS_HOST" >/dev/null 2>&1 || true
            # 取得して known_hosts に追加
            ssh-keyscan -T 5 -H "$CENTOS_HOST" >> ~/.ssh/known_hosts
            # 取れているか検証
            ssh-keygen -F "$CENTOS_HOST" -f ~/.ssh/known_hosts >/dev/null

      - run:
          name: Debug SSH connectivity
          command: |
            set -x
            echo "HOST=$CENTOS_HOST USER=$CENTOS_USER"
            nc -vz "$CENTOS_HOST" 22 || true
            ssh -o ConnectTimeout=10 -v "${CENTOS_USER}@${CENTOS_HOST}" "echo ok"

      - run:
          name: Create directory on CentOS
          command: |
            : "${TARGET_DIR:=/srv/mydir}"
            : "${SSH_PORT:=22}"
            ssh -p "$SSH_PORT" "${CENTOS_USER}@${CENTOS_HOST}" \
              "sudo mkdir -p '${TARGET_DIR}' && sudo chown ${CENTOS_USER}:${CENTOS_USER} '${TARGET_DIR}'"

workflows:
  build:
    jobs:
      - mkdir_on_centos
