version: 2.1

jobs:
  config_cisco:
    machine: true
    resource_class: network001/test001
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:S50sf0kpBGIIAvYaU48X07/Sl6+61J2hnrMbg3dibNY"

      # どの鍵がジョブに入っているか可視化
      - run:
          name: Show the key actually used
          command: |
            set -euxo pipefail
            ssh-add -L || true
            KEY="$(ls -1 ~/.ssh/id_rsa_* | head -n1 || true)"
            echo "Using key: ${KEY:-<not found>}"
            if [ -n "${KEY:-}" ]; then ssh-keygen -lf "$KEY"; fi

      # 疎通スモークテスト（-vvv）
      - run:
          name: Smoke test (show clock with -vvv)
          command: |
            set -euo pipefail
            : "${CISCO_HOST:?CISCO_HOST is required}"

            mkdir -p ~/.ssh && chmod 700 ~/.ssh
            touch ~/.ssh/known_hosts && chmod 600 ~/.ssh/known_hosts
            ssh-keyscan -T 10 -H "$CISCO_HOST" >> ~/.ssh/known_hosts || true

            KEY="$(ls -1 ~/.ssh/id_rsa_* | head -n1)"
            echo "Using key: $KEY"

            ssh -vvv \
              -i "$KEY" \
              -o IdentitiesOnly=yes \
              -o BatchMode=yes \
              -o StrictHostKeyChecking=accept-new \
              -o PubkeyAcceptedKeyTypes=+ssh-rsa \
              -o HostKeyAlgorithms=+ssh-rsa \
              -o KexAlgorithms=+diffie-hellman-group14-sha1 \
              -o Ciphers=+aes256-cbc \
              admin1@"$CISCO_HOST" "show clock"

      # ここまで通ったら設定反映
      - run:
          name: Configure Cisco Hostname
          command: |
            set -euo pipefail
            KEY="$(ls -1 ~/.ssh/id_rsa_* | head -n1)"
            { printf '%s\r\n' \
              'terminal length 0' \
              'configure terminal' \
              'hostname GP-Router' \
              'end' \
              'write memory'; } |
            ssh -tt \
              -i "$KEY" \
              -o IdentitiesOnly=yes \
              -o BatchMode=yes \
              -o StrictHostKeyChecking=accept-new \
              -o PubkeyAcceptedKeyTypes=+ssh-rsa \
              -o HostKeyAlgorithms=+ssh-rsa \
              -o KexAlgorithms=+diffie-hellman-group14-sha1 \
              -o Ciphers=+aes256-cbc \
              admin1@"$CISCO_HOST"

workflows:
  config:
    jobs:
      - config_cisco